POST http://localhost:5002/token
Content-Type: application/json

{
    "username": "Jacob"
}

###
POST http://localhost:5002/verify-token
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjb2IiLCJpYXQiOjE2OTA4NjI1NjksImV4cCI6MTY5MDg2MjU4NH0.0SuWID9BqDLIc30MW3YuTRPxUjjbTmtQQFs3wv3EJ-w"
}

###
POST http://localhost:5002/regenerate-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjb2IiLCJpYXQiOjE2OTA4NjI1NDZ9.1vubug0zkKJ1gUFSgpFCrK7YER3MrX1M_kMCYjeTdm0"
}