apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
  labels:
    app: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security
        image: jangga/security:latest
        ports:
        - containerPort: 40
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: security
  ports:
    - protocol: TCP
      port: 40
      targetPort: 40